config1:
   env: "HRLEnv-v0"
   num_gpus: 0
   num_workers: 3
   framework: "tf2"
   horizon: 500
   clip_rewards: False
   clip_param: 0.5
   sgd_minibatch_size: 128
   train_batch_size: 1024
   num_sgd_iter: 30
   lr: 0.00001
   lambda: 0.95
   kl_coeff: 0.5


